CREATE TABLE API_DOC(
        IDDOC INTEGER PRIMARY KEY UNIQUE NOT NULL,
        NMDOC TEXT NOT NULL,
        TELDOC TEXT NOT NULL,
        CDDOC TEXT NOT NULL,
        NMESPDOC TEXT NULL,
        DCLOGDOC TEXT NULL
);